[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "libmarket"
version = "0.0.1"
dependencies = [
    "requests",
    "SQLAlchemy",
    "psycopg2-binary",
    'importlib-metadata; python_version>="3.10"'
]
